name: cosc4353_volunteer_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  flutter_bloc: ^8.1.6
  another_flushbar: ^1.12.30
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  pdf: ^3.10.4
  csv: ^5.0.2
  share_plus: ^7.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true